geometry_msgs/Pose goal_pose
string object_frame
string world_frame
string mesh_resource
string object_shape
geometry_msgs/Vector3 object_scale
bool enable_aabb_clearing
float32[] object_esdf_clearing_padding
sensor_msgs/JointState seed_state
int32 num_solutions_to_return
---
bool[] success
string message
float32 planning_time
moveit_msgs/MoveItErrorCodes error_code
sensor_msgs/JointState[] joint_states
---
string status
